; route
; applications 向けのルーティング設定を記述します。
; 内線番号を増やす場合、この項目を設定する必要はありません。
;

exten => 186,1,Goto(echo-test,s,1)
exten => 123,1,Goto(hello-world,s,1)
exten => 147,1,Goto(receive-fax,s,1)
exten => 117,1,Goto(my117,s,1)
exten => 100,1,Goto(milliwatt,s,1)
exten => 184,1,Goto(reads-back-number,s,1)
exten => 160,1,Goto(conference,s,1)
