services:
  asterisk:
    container_name: asterisk
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    image: "ghcr.io/tkytel/asterisk-quickstart"
    network_mode: host
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ./config/extensions:/etc/asterisk/extensions
      - ./config/extensions.conf:/etc/asterisk/extensions.conf
      - ./config/logger/logger.conf:/etc/asterisk/logger.conf
      - ./config/modules.conf:/etc/asterisk/modules.conf
      - ./config/musiconhold.conf:/etc/asterisk/musiconhold.conf
      - ./config/pjsip:/etc/asterisk/pjsip
      - ./config/pjsip.conf:/etc/asterisk/pjsip.conf
