[external-trunk-registration](!)
type = registration
transport = transport-v4udp

[external-trunk-auth](!)
type = auth
auth_type = userpass

[external-trunk-aor](!)
type = aor
max_contacts = 3
qualify_frequency = 60

[external-trunk-endpoint](!)
type = endpoint
context = default
allow = all
allow_unauthenticated_options = yes
tone_zone = jp

[external-trunk-identify](!)
type = identify
