; echo-test
; This extension parrots back.

[echo-test]
exten => s,1,Answer()
    same => n,Playback(demo-echotest)
    same => n,Echo()
    same => n,Hangup()

exten => #,1,Playback(goodbye)
    same => n,Hangup()
