; reads-back-number
; This extension reads back the digits entered by the caller after the beep.
; To test this extension, dial 184 from your phone. After the beep, enter a number (up to 16 digits) and it will be read back to you. If you do not enter any digits within 10 seconds, the call will be terminated.

[reads-back-number]
exten => s,1,Answer()
	same => n,Set(TIMEOUT(response)=10)
	same => n,Read(TARGET_NUMBER,beep,16,,1,10)
	same => n,GotoIf($["${TARGET_NUMBER}" = ""]?noinput)
	same => n,SayDigits(${TARGET_NUMBER})
	same => n,Hangup()
	same => n(noinput),NoOp(no digits entered)
	same => n,Hangup()
