; receive-fax
; Receives a fax and saves it to the specified directory.

exten => 147,1,NoOp(receive-fax)
 same => n,Answer()
 same => n,Set(FAXDIR=/var/spool/asterisk/fax/inbound)
 same => n,Set(FAXFILE=${FAXDIR}/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-${CALLERID(num)}-${UNIQUEID}.tif)
 same => n,ReceiveFAX(${FAXFILE},d)
 same => n,NoOp(FAXSTATUS=${FAXSTATUS})
 same => n,NoOp(FAXERROR=${FAXERROR})
 same => n,NoOp(FAXSTATUSSTRING=${FAXSTATUSSTRING})
 same => n,NoOp(FAXPAGES=${FAXPAGES})
 same => n,Hangup()
