[SIP-TRUNK-INBOUND]
type = auth
username = SIP-TRUNK-INBOUND
password = SIP-TRUNK-INBOUND

[SIP-TRUNK-INBOUND]
type = aor
max_contacts = 1024
qualify_frequency = 60

[SIP-TRUNK-INBOUND]
type = endpoint
100rel = no
context = default
dtmf_mode = auto

;Codec negotiation order
disallow = all
allow = g722
allow = alaw
allow = ulaw
allow = ilbc
allow = h264

rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
ice_support = no
direct_media = yes
sdp_session = asterisk
language = ja
aors = SIP-TRUNK-INBOUND
timers = no
rtp_timeout = 30
rtp_timeout_hold = 30
auth = SIP-TRUNK-INBOUND
inband_progress = yes
tone_zone = jp
