[general]
writeprotect=no

[globals]
MORSEDITLEN=60

[default]

; Telephones
#include "extensions/internal/*.conf"

; Applications
#include "extensions/applications/*.conf"

; external SIP trunks
#include "extensions/external/*.conf"

exten => _X.,1,NoOp(Catch invalid number: ${EXTEN})
    same => n,Set(CHANNEL(language)=ja)
    same => n,Playback(ss-noservice)
    same => n,Hangup()
