[general]
writeprotect=no

[globals]
MORSEDITLEN=60
#include "extensions/applications/*.conf"

[default]
#include "extensions/external/*.conf"
#include "extensions/internal/*.conf"
#include "extensions/hop.conf"
#include "extensions/route.conf"

exten => _X.,1,NoOp(Catch invalid number: ${EXTEN})
    same => n,Set(CHANNEL(language)=ja)
    same => n,Playback(ss-noservice)
    same => n,Hangup()
