[transport-v4udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
allow_reload=yes

[transport-v6udp]
type=transport
protocol=udp
bind=[::]:5060
allow_reload=yes

#include "pjsip/internal/*.conf"
#include "pjsip/external/*.conf"
